//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPKey.Messages {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FTPKey.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore di autenticazione con il server remoto, controllare i parametri di autenticazione.
        /// </summary>
        internal static string AuthenticationExceptionMessage {
            get {
                return ResourceManager.GetString("AuthenticationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore nella connessione con il server remoto: {0}.
        /// </summary>
        internal static string ConnectionExceptionMessage {
            get {
                return ResourceManager.GetString("ConnectionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore nella cancellazione della cartella {0}, la cartella non è vuota.
        /// </summary>
        internal static string DeleteFolderNotEmpty {
            get {
                return ResourceManager.GetString("DeleteFolderNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante l&apos;operazione {0}: {1}.
        /// </summary>
        internal static string GenericException {
            get {
                return ResourceManager.GetString("GenericException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SetDirectory.
        /// </summary>
        internal static string OperationChangeDirectory {
            get {
                return ResourceManager.GetString("OperationChangeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CreateFolder.
        /// </summary>
        internal static string OperationCreateFolder {
            get {
                return ResourceManager.GetString("OperationCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete.
        /// </summary>
        internal static string OperationDelete {
            get {
                return ResourceManager.GetString("OperationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DeleteFolder.
        /// </summary>
        internal static string OperationDeleteFolder {
            get {
                return ResourceManager.GetString("OperationDeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Download.
        /// </summary>
        internal static string OperationDownload {
            get {
                return ResourceManager.GetString("OperationDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GetFilesList.
        /// </summary>
        internal static string OperationGetFilesList {
            get {
                return ResourceManager.GetString("OperationGetFilesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GetFoldersList.
        /// </summary>
        internal static string OperationGetFoldersList {
            get {
                return ResourceManager.GetString("OperationGetFoldersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante l&apos;operazione {0} del file {1}, l&apos;operazione non è stata completata correttamente.
        /// </summary>
        internal static string OperationNotCompletedException {
            get {
                return ResourceManager.GetString("OperationNotCompletedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a RenameFile.
        /// </summary>
        internal static string OperationRenameFile {
            get {
                return ResourceManager.GetString("OperationRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Upload.
        /// </summary>
        internal static string OperationUpload {
            get {
                return ResourceManager.GetString("OperationUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lo stream di destinazione non può essere null.
        /// </summary>
        internal static string OutStreamNullExceptionMessage {
            get {
                return ResourceManager.GetString("OutStreamNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante l&apos;operazione {0}, non è stato trovato il percorso {1}.
        /// </summary>
        internal static string PathNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("PathNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore di permessi durante l&apos;operazione {0}, non si dispone di permessi sufficienti per svolgere l&apos;operazione.
        /// </summary>
        internal static string PermissionDeniedExceptionMessage {
            get {
                return ResourceManager.GetString("PermissionDeniedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il file &apos;{0}&apos; non è stato trovato.
        /// </summary>
        internal static string UploadFileNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("UploadFileNotFoundExceptionMessage", resourceCulture);
            }
        }
    }
}
